networks:
  frontend:
  backend:

services:
  front:
    image: ghcr.io/corona-travel/ctf:latest
    networks:
      - frontend
      - backend
    ports:
      - 80:3000

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 443:443
    networks:
      - backend

  mongo:
    image: mongo:5
    networks:
      - backend
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/corona_travel --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017

  facts:
    image: ghcr.io/corona-travel/facts:latest
    command: uvicorn --host 0.0.0.0 --port 1234 facts.app:app --root-path /facts
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend

#  media:
#    image: ghcr.io/corona-travel/media:latest
#    command: uvicorn --host 0.0.0.0 --port 1234 media.app:app --root-path /media
#    environment:
#      MONGO_URL: mongodb://mongo/corona_travel
#      LOG_LEVEL: DEBUG
#    networks:
#      - backend

  places:
    image: ghcr.io/corona-travel/places:latest
    command: uvicorn --host 0.0.0.0 --port 1234 places.app:app --root-path /places
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend

  quizzes:
    image: ghcr.io/corona-travel/quizzes:latest
    command: uvicorn --host 0.0.0.0 --port 1234 quizzes.app:app --root-path /quizzes
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend


