networks:
  frontend:
  backend:

services:
  front:
    image: ""
    networks:
      - frontend
    ports:
      - 80:3000

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 443:443
    networks:
      - backend

  mongo:
    image: mongo:5
    networks:
      - backend
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/corona_travel --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017

  facts:
    image: ghcr.io/corona-travel/facts:latest
    command: uvicorn --host 0.0.0.0 --port 1234 facts.app:app --root-path /facts
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend
    ports:
      - 12341:1234



